### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by 1337r00t** [r3m0t3nu11/simple-file-bypass#1]
https://github.com/r3m0t3nu11/simple-file-bypass/blob/834d9029b2208d9915489941c6b4aeee490c529f/simple-bypass-ruby-readfile.rb#L51

To :- 
      `r3m0t3nu11 = red(open("/b'i'n/c'a't /e't'c/p'a's's'w'd'").read)`

**Comment by r3m0t3nu11** [comment]
Thanks for ur notice
